# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70280e752d140939901936270587441f3d9b95f7d8c8086ac1e2e613ab5e9f5d332078ac4015aa6588e601dda1df7a7d5f0fbbeda27780c1e03e8ce60d833485
  url: http://localhost:3000

test:
  secret_key_base: 266121b0458d133fc032c97851b3d3f2ee75133fc6edaf43b5105d77c2840a49365838f4e9e1f55371b223ca9c83616562e8634939a2e1cebf805c41c6d30c4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
